/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.change2projectname.view;

import edu.chl.change2projectname.controller.ProjectController;
import edu.chl.change2projectname.model.Activity;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;

/**
 *
 * @author cain
 */
public class AddActivityCard extends javax.swing.JPanel {

    /**
     * Creates new form AddActivityCard
     */
    public AddActivityCard() {
        initComponents();
        initComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameTextfield = new javax.swing.JTextField();
        startDateLabel = new javax.swing.JLabel();
        sDayComboBox = new javax.swing.JComboBox();
        sMonthComboBox = new javax.swing.JComboBox();
        sYearComboBox = new javax.swing.JComboBox();
        sHourComboBox = new javax.swing.JComboBox();
        sMinuteComboBox = new javax.swing.JComboBox();
        endDateLabel = new javax.swing.JLabel();
        eDayComboBox = new javax.swing.JComboBox();
        eMonthComboBox = new javax.swing.JComboBox();
        eYearComboBox = new javax.swing.JComboBox();
        eHourComboBox = new javax.swing.JComboBox();
        eMinuteComboBox = new javax.swing.JComboBox();
        locationLabel = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 600));

        nameLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        nameLabel.setText("Name*");

        startDateLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        startDateLabel.setText("Startdate*");

        sDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));

        sMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        sYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015" }));

        sHourComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        sMinuteComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        endDateLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        endDateLabel.setText("Enddate*");

        eDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));

        eMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        eYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015" }));

        eHourComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        eMinuteComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        locationLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        locationLabel.setText("Location");

        descriptionLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        descriptionLabel.setText("Description");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        saveButton.setText("Save");

        cancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateLabel)
                            .addComponent(endDateLabel)
                            .addComponent(locationLabel)
                            .addComponent(descriptionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(eDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(eHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(sHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(nameTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(locationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(284, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JComboBox eDayComboBox;
    private javax.swing.JComboBox eHourComboBox;
    private javax.swing.JComboBox eMinuteComboBox;
    private javax.swing.JComboBox eMonthComboBox;
    private javax.swing.JComboBox eYearComboBox;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JComboBox sDayComboBox;
    private javax.swing.JComboBox sHourComboBox;
    private javax.swing.JComboBox sMinuteComboBox;
    private javax.swing.JComboBox sMonthComboBox;
    private javax.swing.JComboBox sYearComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel startDateLabel;
    // End of variables declaration//GEN-END:variables

    public Activity getAsActivity(){
        //TODO: Handle errors when missing fields not in there... Maybe disable Save button?
        String name = nameTextfield.getText();
        Calendar startDate = Calendar.getInstance();
        int sYear = (Integer) sYearComboBox.getSelectedItem();
        int sMonth = sMonthComboBox.getSelectedIndex();
        int sDay = sDayComboBox.getSelectedIndex()+1;
        int sHour = Integer.parseInt((String) sHourComboBox.getSelectedItem());
        int sMinute = Integer.parseInt((String) sMinuteComboBox.getSelectedItem());
        startDate.set(sYear, sMonth, sDay, sHour, sMinute);
        Calendar endDate = Calendar.getInstance();
        int eYear = (Integer) eYearComboBox.getSelectedItem();
        int eMonth = eMonthComboBox.getSelectedIndex();
        int eDay = eDayComboBox.getSelectedIndex()+1;
        int eHour = Integer.parseInt((String) eHourComboBox.getSelectedItem());
        int eMinute = Integer.parseInt((String) eMinuteComboBox.getSelectedItem());
        endDate.set(eYear, eMonth, eDay, eHour, eMinute);
        String location = locationTextField.getText();
        String description = descriptionTextArea.getText();
        Activity a = new Activity(startDate, endDate, name);
        a.setLocation(location);
        a.setDescription(description);
        return a;
    }
    
    /*
    public void registerListener(ProjectController controller){
        saveButton.addActionListener(controller);
        cancelButton.addActionListener(controller);
    }
    */
    
    public JButton getSaveButton(){
        return saveButton;
    }
    
    public JButton getCancelButton(){
        return cancelButton;
    }
    
    private void initComboBoxes() {
        // Set the days
        sDayComboBox.removeAllItems();
        eDayComboBox.removeAllItems();
        for (int i = 1; i <= 31; i++) {
            sDayComboBox.addItem(i);
            eDayComboBox.addItem(i);
        }
        // Set the months
//        String[] months = { "January", "February", "March", "April", "May", "June",
//            "July", "August", "September", "October", "November", "December" };
//        sMonthComboBox.removeAllItems();
//        eMonthComboBox.removeAllItems();
//        sMonthComboBox.addItem(months);
//        eMonthComboBox.addItem(months);
        // Set the years
        sYearComboBox.removeAllItems();
        eYearComboBox.removeAllItems();
        for (int i = 2015; i <= 2020; i++) {
            sYearComboBox.addItem(i);
            eYearComboBox.addItem(i);
        }
        // Set the hours
//        sHourComboBox.removeAllItems();
//        eHourComboBox.removeAllItems();
//        for (int i = 0; i <= 23; i++) {
//            sHourComboBox.addItem(i);
//            eHourComboBox.addItem(i);
//        }
        // Set the minutes
        //sMinuteComboBox.removeAllItems();
        //eMinuteComboBox.removeAllItems();
//        for (int i = 10; i <= 55; i = i+5) {
//            sMinuteComboBox.addItem(i);
//            eMinuteComboBox.addItem(i);
//        }
        
        }
}
