/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.change2projectname.view;

import edu.chl.change2projectname.model.ContactGroup;
import java.awt.Dimension;
import java.util.List;

/**
 *
 * @author cain
 */
public class ContactGroupCard extends javax.swing.JPanel {

    /**
     * Creates new form ContactGroupCard
     */
    public ContactGroupCard() {
        initComponents();
        contactGroupScrollPane.getVerticalScrollBar().setUnitIncrement(20);
    }
    
    public void updateContactGroups(List<ContactGroup> contactgroups) {
        elementList.removeAll();
        elementList.setPreferredSize(new Dimension(684,500));
        elementList.setSize(684, 500);
        for (ContactGroup cg: contactgroups) {
            ContactGroupElement cge = new ContactGroupElement(cg);
            cge.setPreferredSize(new Dimension(400,47));
            elementList.add(cge);
            revalidate();
            repaint();
            revalidate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactGroupScrollPane = new javax.swing.JScrollPane();
        elementList = new javax.swing.JPanel();

        contactGroupScrollPane.setViewportView(elementList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contactGroupScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contactGroupScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contactGroupScrollPane;
    private javax.swing.JPanel elementList;
    // End of variables declaration//GEN-END:variables
}
