/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.change2projectname.view;

import edu.chl.change2projectname.model.Project;

/**
 *
 * @author cain
 */
public class ProjectView extends javax.swing.JFrame {

    /**
     * Creates new form ProjectView
     */
    public ProjectView() {
        initComponents();
    }

    public ProjectView(Project project) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        menuPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        logoSeparator = new javax.swing.JSeparator();
        menuCalendarLabel = new javax.swing.JLabel();
        menuCalenderPanel = new javax.swing.JPanel();
        newActivityLabel = new javax.swing.JLabel();
        listViewLabel = new javax.swing.JLabel();
        weekViewLabel = new javax.swing.JLabel();
        monthViewLabel = new javax.swing.JLabel();
        menuContactsLabel = new javax.swing.JLabel();
        menuContactsPanel = new javax.swing.JPanel();
        newContactsLabel = new javax.swing.JLabel();
        newGroupLabel = new javax.swing.JLabel();
        allContactsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuSettingsLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        menuPanel.setBackground(new java.awt.Color(63, 81, 181));
        menuPanel.setPreferredSize(new java.awt.Dimension(300, 700));

        logoLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("Kalender++_logo");

        menuCalendarLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        menuCalendarLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuCalendarLabel.setIcon(new javax.swing.ImageIcon("/home/cain/arrow_down.png")); // NOI18N
        menuCalendarLabel.setText("Calendar");

        menuCalenderPanel.setBackground(new java.awt.Color(63, 81, 181));

        newActivityLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        newActivityLabel.setForeground(java.awt.Color.white);
        newActivityLabel.setText("Add an activity");

        listViewLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        listViewLabel.setForeground(java.awt.Color.white);
        listViewLabel.setText("Listview");

        weekViewLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        weekViewLabel.setForeground(java.awt.Color.white);
        weekViewLabel.setText("Weekview");

        monthViewLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        monthViewLabel.setForeground(java.awt.Color.white);
        monthViewLabel.setText("Monthview");

        javax.swing.GroupLayout menuCalenderPanelLayout = new javax.swing.GroupLayout(menuCalenderPanel);
        menuCalenderPanel.setLayout(menuCalenderPanelLayout);
        menuCalenderPanelLayout.setHorizontalGroup(
            menuCalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCalenderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuCalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newActivityLabel)
                    .addComponent(listViewLabel)
                    .addComponent(weekViewLabel)
                    .addComponent(monthViewLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuCalenderPanelLayout.setVerticalGroup(
            menuCalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCalenderPanelLayout.createSequentialGroup()
                .addComponent(newActivityLabel)
                .addGap(18, 18, 18)
                .addComponent(listViewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekViewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthViewLabel))
        );

        menuContactsLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        menuContactsLabel.setForeground(java.awt.Color.white);
        menuContactsLabel.setIcon(new javax.swing.ImageIcon("/home/cain/arrow_down.png")); // NOI18N
        menuContactsLabel.setText("Contacts");

        menuContactsPanel.setBackground(new java.awt.Color(63, 81, 181));

        newContactsLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        newContactsLabel.setForeground(java.awt.Color.white);
        newContactsLabel.setText("Add new contact");

        newGroupLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        newGroupLabel.setForeground(java.awt.Color.white);
        newGroupLabel.setText("Add new group");

        allContactsLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        allContactsLabel.setForeground(java.awt.Color.white);
        allContactsLabel.setText("All contacts");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Family");

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Work");

        javax.swing.GroupLayout menuContactsPanelLayout = new javax.swing.GroupLayout(menuContactsPanel);
        menuContactsPanel.setLayout(menuContactsPanelLayout);
        menuContactsPanelLayout.setHorizontalGroup(
            menuContactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContactsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuContactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newContactsLabel)
                    .addComponent(newGroupLabel)
                    .addComponent(allContactsLabel)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuContactsPanelLayout.setVerticalGroup(
            menuContactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContactsPanelLayout.createSequentialGroup()
                .addComponent(newContactsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newGroupLabel)
                .addGap(18, 18, 18)
                .addComponent(allContactsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );

        menuSettingsLabel.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        menuSettingsLabel.setForeground(java.awt.Color.white);
        menuSettingsLabel.setIcon(new javax.swing.ImageIcon("/home/cain/arrow_right.png")); // NOI18N
        menuSettingsLabel.setText("Settings");

        searchTextField.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        searchTextField.setText("Search...");

        jButton1.setText("Hokuspokus");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(logoSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(menuCalenderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menuCalendarLabel)
                                    .addComponent(menuContactsLabel))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(menuContactsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuSettingsLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuCalendarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuCalenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuContactsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuContactsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuSettingsLabel)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jLayeredPane1.setLayer(menuPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allContactsLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel listViewLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JSeparator logoSeparator;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menuCalendarLabel;
    private javax.swing.JPanel menuCalenderPanel;
    private javax.swing.JLabel menuContactsLabel;
    private javax.swing.JPanel menuContactsPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel menuSettingsLabel;
    private javax.swing.JLabel monthViewLabel;
    private javax.swing.JLabel newActivityLabel;
    private javax.swing.JLabel newContactsLabel;
    private javax.swing.JLabel newGroupLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel weekViewLabel;
    // End of variables declaration//GEN-END:variables
}
