/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.calendarplusplus.alarmnotification;

import edu.chl.calendarplusplus.alarmnotification.IAlarm;
import java.awt.Dimension;
import java.beans.PropertyChangeSupport;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author cain
 */
public class AlarmCard extends javax.swing.JPanel {

    private PropertyChangeSupport pcs;
    private final int alarmwidth = 650;
    private final int alarmheight = 114;
    /**
     * Creates new form AlarmCard
     */
    public AlarmCard() {
        initComponents();
        listViewScrollPane.getVerticalScrollBar().setUnitIncrement(20);
    }
    
    public void updateAlarms (List<IAlarm> alarmlist) {
        Collections.sort(alarmlist);
        elementList.removeAll();
        elementList.setPreferredSize(new Dimension(alarmwidth,alarmlist.size()*(alarmheight+5) + 5));
        for (IAlarm a : alarmlist) {
            AlarmElement ale = new AlarmElement(a);
            ale.setPreferredSize(new Dimension(alarmwidth,alarmheight));
            ale.addListener(pcs);
            elementList.add(ale);
            revalidate();
            repaint();
            revalidate();
        }
        revalidate();
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listViewScrollPane = new javax.swing.JScrollPane();
        elementList = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(710, 850));

        listViewScrollPane.setViewportView(elementList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listViewScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listViewScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel elementList;
    private javax.swing.JScrollPane listViewScrollPane;
    // End of variables declaration//GEN-END:variables

    public void addListener(PropertyChangeSupport pcs) {
        this.pcs = pcs;
    }
}
