/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.calendarplusplus.contact;

import edu.chl.calendarplusplus.contact.IContact;
import java.awt.Dimension;
import java.beans.PropertyChangeSupport;
import java.util.Collections;
import java.util.List;
import org.eclipse.persistence.internal.core.helper.CoreClassConstants;

/**
 *
 * @author cain
 */
public class ContactCard extends javax.swing.JPanel {

    int elementheight = 107;
    private PropertyChangeSupport pcs;
    
    /**
     * Creates new form ContactCard
     */
    public ContactCard() {
        initComponents();
        contactScrollPane.getVerticalScrollBar().setUnitIncrement(20);
    }
    
    public void updateContacts(List<IContact> contactlist){
        Collections.sort(contactlist);
        int height = contactlist.size() % 2 == 0 ? (1+contactlist.size()/2)*15 + contactlist.size()/2*elementheight : (1+contactlist.size()/2)*15 + (contactlist.size()/2+1)*elementheight;
        elementList.removeAll();
        elementList.setPreferredSize(new Dimension(1008,height));
        for (IContact c: contactlist) {
            ContactElement ce = new ContactElement(c);
            ce.setPreferredSize(new Dimension((elementList.getPreferredSize().width-60)/2,elementheight));
            ce.addListener(pcs);
            elementList.add(ce);
            revalidate();
            repaint();
            revalidate();
        }
        revalidate();
        repaint();
        revalidate();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactScrollPane = new javax.swing.JScrollPane();
        elementList = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1008, 640));

        contactScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        elementList.setPreferredSize(new java.awt.Dimension(1006, 638));
        elementList.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 15, 15));
        contactScrollPane.setViewportView(elementList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contactScrollPane;
    private javax.swing.JPanel elementList;
    // End of variables declaration//GEN-END:variables
    
    public void addListener(PropertyChangeSupport pcs) {
        this.pcs = pcs;
    }

}
