/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.calendarplusplus.contact;

import edu.chl.calendarplusplus.contact.ContactGroup;
import edu.chl.calendarplusplus.contact.IContactGroup;
import java.awt.Dimension;
import java.beans.PropertyChangeSupport;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author cain
 */
public class ContactGroupCard extends javax.swing.JPanel {
    
    int elementheight = 100;
    private PropertyChangeSupport pcs;
    
    /**
     * Creates new form ContactGroupCard
     */
    public ContactGroupCard() {
        initComponents();
        contactGroupScrollPane.getVerticalScrollBar().setUnitIncrement(20);
    }
    
    public void updateContactGroups(List<IContactGroup> contactgroups) {
        IContactGroup def = new ContactGroup();
        def = contactgroups.get(0);
        contactgroups.remove(0);
        Collections.sort(contactgroups);
        contactgroups.add(0, def);
        
        int height = contactgroups.size() % 2 == 0 ? (1+contactgroups.size()/2)*15 + contactgroups.size()/2*elementheight : (1+contactgroups.size()/2)*15 + (contactgroups.size()/2+1)*elementheight;
        elementList.removeAll();
        elementList.setPreferredSize(new Dimension(1008,height));
        for (IContactGroup cg: contactgroups) {
            ContactGroupElement cge = new ContactGroupElement(cg);
            cge.setPreferredSize(new Dimension((elementList.getPreferredSize().width-60)/2,elementheight));
            cge.addListener(pcs);
            elementList.add(cge);
            revalidate();
            repaint();
            revalidate();
        }
        revalidate();
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactGroupScrollPane = new javax.swing.JScrollPane();
        elementList = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1008, 640));

        contactGroupScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        contactGroupScrollPane.setPreferredSize(new java.awt.Dimension(1008, 640));

        elementList.setPreferredSize(new java.awt.Dimension(1006, 638));
        elementList.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 15, 15));
        contactGroupScrollPane.setViewportView(elementList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactGroupScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactGroupScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contactGroupScrollPane;
    private javax.swing.JPanel elementList;
    // End of variables declaration//GEN-END:variables

    public void addListener(PropertyChangeSupport pcs) {
        this.pcs = pcs;
    }
}
