/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.calendarplusplus.view;

import edu.chl.calendarplusplus.model.IContactGroup;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;

/**
 *
 * @author cain
 */
public class ContactGroupCard extends javax.swing.JPanel {

    /**
     * Creates new form ContactGroupCard
     */
    public ContactGroupCard() {
        initComponents();
        ((FlowLayout)elementList.getLayout()).setHgap(20);
        ((FlowLayout)elementList.getLayout()).setVgap(20);
        contactGroupScrollPane.getVerticalScrollBar().setUnitIncrement(20);
    }
    
    public void updateContactGroups(List<IContactGroup> contactgroups) {
        elementList.removeAll();
//        elementList.setPreferredSize(new Dimension(684,500));
//        elementList.setSize(684, 500);
        for (IContactGroup cg: contactgroups) {
            ContactGroupElement cge = new ContactGroupElement(cg);
            cge.setPreferredSize(new Dimension(elementList.getPreferredSize().width/2-20,90));
            elementList.add(cge);
            revalidate();
            repaint();
            revalidate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactGroupScrollPane = new javax.swing.JScrollPane();
        elementList = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1008, 652));

        contactGroupScrollPane.setPreferredSize(new java.awt.Dimension(1008, 652));

        elementList.setPreferredSize(new java.awt.Dimension(1006, 650));
        contactGroupScrollPane.setViewportView(elementList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactGroupScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactGroupScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contactGroupScrollPane;
    private javax.swing.JPanel elementList;
    // End of variables declaration//GEN-END:variables
}
