/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.calendarplusplus.view;

import java.awt.Color;
import static java.time.temporal.ChronoField.MONTH_OF_YEAR;
import java.util.Calendar;

/**
 *
 * @author erikforsberg
 */
public class MonthViewCard extends javax.swing.JPanel {
    
    /**
     * Creates new form MonthViewCard
     */
    private Calendar currentDate;
    private Boolean previousButtonPressed;
    private Boolean nextButtonPressed;
    
    public MonthViewCard() {
        initComponents();
        currentDate = Calendar.getInstance();
        updateMonthView();
    }
    
    public void updateMonthView(){
        updateMonthStatic(currentDate);
        setMonthName();
    }
    
    public void setMonthName(){
    String[] monthNames = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
    int month = currentDate.get(Calendar.MONTH);
    monthLabel.setText(monthNames[month]+ " " + currentDate.get(Calendar.YEAR));

    }
    
    /*
    Updates the monthview and sets all attributes. Including colors, week
    number, day number etc.
    */
    
    public void updateMonthStatic(Calendar c){
        
        dayPanel.removeAll();
        boolean setWeek = false;
        Calendar today = Calendar.getInstance();
        Calendar tempDate = Calendar.getInstance();
        
        tempDate.set(c.get(Calendar.YEAR), c.get(Calendar.MONTH), 0);
        int diff = 1 - tempDate.get(Calendar.DAY_OF_WEEK);
        tempDate.add(Calendar.DATE, diff);
        
        for(int i = 0; i <= 41; i++){
            if(i%7 == 0){
                setWeek = true;
            }else{
                setWeek = false;
            }
            tempDate.add(Calendar.DATE, 1);
            
            MonthViewElementCard mvec = 
                    new MonthViewElementCard(tempDate.get(Calendar.DATE),
                    tempDate.get(Calendar.WEEK_OF_YEAR),
                    tempDate.get(Calendar.DAY_OF_YEAR), setWeek);
            
            if(!(tempDate.get(Calendar.MONTH) == currentDate.get(Calendar.MONTH))){
                mvec.setBackground(Color.LIGHT_GRAY);
            }else if((tempDate.get(Calendar.DATE) == today.get(Calendar.DATE))
                        && (tempDate.get(Calendar.MONTH) == today.get(Calendar.MONTH))
                        && (tempDate.get(Calendar.YEAR) == today.get(Calendar.YEAR))){
                mvec.setBackground(new Color(255, 140, 140));
            }
            dayPanel.add(mvec);
            revalidate();
            repaint();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        monthLabel = new javax.swing.JLabel();
        nextMonthButton = new javax.swing.JLabel();
        previousMonthButton = new javax.swing.JLabel();
        staticDayPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dayPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1008, 640));

        topPanel.setPreferredSize(new java.awt.Dimension(1008, 104));

        monthLabel.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        monthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthLabel.setText("#Month");

        nextMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowsRight.png"))); // NOI18N
        nextMonthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextMonthButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextMonthButtonMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextMonthButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextMonthButtonMouseEntered(evt);
            }
        });

        previousMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowsLeft.png"))); // NOI18N
        previousMonthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                previousMonthButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                previousMonthButtonMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                previousMonthButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                previousMonthButtonMouseEntered(evt);
            }
        });

        staticDayPanel.setPreferredSize(new java.awt.Dimension(1008, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Monday");
        jLabel2.setPreferredSize(new java.awt.Dimension(134, 16));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tuesday");
        jLabel3.setPreferredSize(new java.awt.Dimension(134, 16));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Wednesday");
        jLabel4.setPreferredSize(new java.awt.Dimension(134, 16));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thursday");
        jLabel5.setPreferredSize(new java.awt.Dimension(134, 16));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Friday");
        jLabel6.setPreferredSize(new java.awt.Dimension(134, 16));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Saturday");
        jLabel7.setPreferredSize(new java.awt.Dimension(134, 16));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sunday");
        jLabel8.setPreferredSize(new java.awt.Dimension(134, 16));

        javax.swing.GroupLayout staticDayPanelLayout = new javax.swing.GroupLayout(staticDayPanel);
        staticDayPanel.setLayout(staticDayPanelLayout);
        staticDayPanelLayout.setHorizontalGroup(
            staticDayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staticDayPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staticDayPanelLayout.setVerticalGroup(
            staticDayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staticDayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staticDayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(previousMonthButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextMonthButton)
                .addContainerGap(356, Short.MAX_VALUE))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(staticDayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextMonthButton)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(previousMonthButton)
                        .addComponent(monthLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staticDayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dayPanel.setPreferredSize(new java.awt.Dimension(1006, 600));
        dayPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void previousMonthButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMonthButtonMousePressed
       previousButtonPressed = true;
    }//GEN-LAST:event_previousMonthButtonMousePressed

    private void previousMonthButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMonthButtonMouseReleased
        if(previousButtonPressed){
            currentDate.add(Calendar.MONTH, -1);
            updateMonthStatic(currentDate);
            setMonthName();
        }
    }//GEN-LAST:event_previousMonthButtonMouseReleased

    private void nextMonthButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMonthButtonMousePressed
        nextButtonPressed = true;
    }//GEN-LAST:event_nextMonthButtonMousePressed

    private void nextMonthButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMonthButtonMouseReleased
        if(nextButtonPressed){
            currentDate.add(Calendar.MONTH, 1);
            updateMonthStatic(currentDate);
            setMonthName();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_nextMonthButtonMouseReleased

    private void previousMonthButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMonthButtonMouseEntered
        previousMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowsLeftHover.png")));
    }//GEN-LAST:event_previousMonthButtonMouseEntered

    private void previousMonthButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMonthButtonMouseExited
        previousMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowsLeft.png")));
    }//GEN-LAST:event_previousMonthButtonMouseExited

    private void nextMonthButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMonthButtonMouseEntered
        nextMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowsRightHover.png")));
    }//GEN-LAST:event_nextMonthButtonMouseEntered

    private void nextMonthButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMonthButtonMouseExited
        nextMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowsRight.png")));
    }//GEN-LAST:event_nextMonthButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dayPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel nextMonthButton;
    private javax.swing.JLabel previousMonthButton;
    private javax.swing.JPanel staticDayPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
